### ISSUE TITLE
Add IPv6 Shoot example to the usage docs

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#1134]
**How to categorize this issue?**

/area networking
/kind enhancement
/platform aws

**What would you like to be added**:
https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage/usage.md contains the following Shoot examples - single zone Shoot, multiple zone Shoot.
I would be great if Shoot using ipv6 example is added.

**Why is this needed**:
Document the new features so that end users can create ipv6 Shoot without issues.

**Comment by ialidzhikov** [comment]
cc @DockToFuture @axel7born @ScheererJ

**Comment by DockToFuture** [comment]
https://github.com/gardener/gardener-extension-provider-aws/pull/1135
