### ISSUE TITLE
Infrastructure controller can wrongly early exit on deletion

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#121]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal
/platform aws

**What happened**:
Currently the infrastructure deletion can wrongly exit on detecting empty state and assuming that nothing was creating (because of invalid credentials or other reason).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an Infrastructure with terraform config that will timeout out to be created.

2. Delete the Infrastructure.

3. Ensure that the terraformer Pod from the creation can still run but the infrastructure controller can proceed with the deletion detecting empty terraform state config map and removing the Infrastucture finalizer.

Generally this can happen as the terraform pkg is only deleting the Pod and does not wait until the deletion happens after the grace period of time. The infra deletion can meanwhile wrongly complete when the state is empty but there is a terminating terraformer Pod.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): v1.5.2
- Extension version: v1.8.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by tim-ebert** [comment]
@ialidzhikov Am I seeing it correctly, that this can only happen if the `provider-aws` Pod got evicted/killed or leadership changed?
Otherwise an ongoing reconcile iteration would block the deletion request until the terraformer Pod is deleted, right?

**Comment by ialidzhikov** [comment]
The terraformer pkg is only deleting the Pod but it does not wait until it is terminated.

https://github.com/gardener/gardener/blob/19c7a5c19fd5d57a84ddd3b77ad2ed7380f05a91/extensions/pkg/terraformer/terraformer.go#L216-L218

You could have a reconcile that leaves such Pod that can exist for `630s` and if it is the initial run, the terraform state would be still empty. And if the infra is deleted meanwhile, the infra_controller would early exit which is kind of wrong as we still have a terminating terraformer Pod that has some state.

**Comment by tim-ebert** [comment]
Hmmm, while looking into it I found out, that the `execute` func actually waits for other pods to be deleted here: https://github.com/gardener/gardener/blob/19c7a5c19fd5d57a84ddd3b77ad2ed7380f05a91/extensions/pkg/terraformer/terraformer.go#L151

But nevertheless, I would actually go for removing the early exit in the infra controller (https://github.com/gardener/gardener-extension-provider-aws/blob/b045979ea02f8b0d81b81df298458862dfb52677/pkg/controller/infrastructure/actuator_delete.go#L54-L60), as the terraformer package also does this check already: https://github.com/gardener/gardener/blob/19c7a5c19fd5d57a84ddd3b77ad2ed7380f05a91/extensions/pkg/terraformer/terraformer.go#L173-L179

I have to do some more tests and check, that this would not break deleting an infrastructure which was created with invalid secrets and I can open a PR with that.

**Comment by ialidzhikov** [comment]
> But nevertheless, I would actually go for removing the early exit in the infra controller (https://github.com/gardener/gardener-extension-provider-aws/blob/b045979ea02f8b0d81b81df298458862dfb52677/pkg/controller/infrastructure/actuator_delete.go#L54-L60), as the terraformer package also does this check already: https://github.com/gardener/gardener/blob/19c7a5c19fd5d57a84ddd3b77ad2ed7380f05a91/extensions/pkg/terraformer/terraformer.go#L173-L179

The early exit was introduced to handle the issue described in https://github.com/gardener/gardener-extension-provider-aws/issues/18 - to allow the deletion of infra which was potentially never created (because of invalid credentials for example).

**Comment by tim-ebert** [comment]
Yep, saw that. Let me validate, that my proposed changed does not regress the mentioned issue.

**Comment by ialidzhikov** [comment]
I think I saw a minor issue with it. If the infrastructure deletion is interrupted because of controller restart for example and leaves a terraformer Pod without a deletion timestamp, then the next infra deletion waits forever for clean environment.

```
$ k -n shoot--it--tmppi-cr1 get po
NAME                               READY   STATUS    RESTARTS   AGE
etcd-events-0                      2/2     Running   0          6h45m
etcd-main-0                        2/2     Running   0          6h44m
tmppi-cr1.infra.tf-destroy-kcs5s   0/1     Error     0          67m
```

**Comment by rfranzke** [comment]
Yes, thanks @ialidzhikov, I saw the same and talked to @tim-ebert about it. We probably should use `EnsureCleanedUp` in the deletion flow.

**Comment by tim-ebert** [comment]
Yes, will do 👍
