### ISSUE TITLE
Enable encryption on disks attached to AWS VMs 

### ISSUE THREAD

**Issue by prashanth26** [gardener/gardener-extension-provider-aws#126]
**How to categorize this issue?**

/area security
/kind enhancement
/priority normal
/platform aws

**What would you like to be added**:
Encryption to be enabled by default for all disks attached to EC2 instances

**Why is this needed**:
Security

**Comment by rfranzke** [comment]
Probably it should not. AFAIK there are machine types which don't support this, so enabling it by default might break such scenarios, or?

**Comment by prashanth26** [comment]
Yes, it could. 

As suggested by @vlerenc, we could enable encryption by default, and shoot owners can opt-out (by setting the flag on the worker pool to disable encryption) in scenarios where encryption isn't supported.

**Comment by prashanth26** [comment]
If this enhancement is required. I have made the one line change here - https://github.com/prashanth26/gardener-extension-provider-aws/commit/5f0b4778b1c7c1d9d2fc68dfd8ff6cab40e71202. I have tested it with a running shoot and seems to work fine. Existing shoots are able to create new machines without a rolling update with this change. 

cc: @amshuman-kr @hardikdr

**Comment by rfranzke** [comment]
Sure, agreed.

**Comment by guydaichs** [comment]
@prashanth26, @rfranzke   - would this cause a node rolling update for existing clusters that don't set the encryption flag for worker volumes?

**Comment by rfranzke** [comment]
@guydaichs No, it won't cause a rolling update. Anybody who wants encrypted disks would have to recreate his nodes or set the `encrypted` field to `true` in the `Shoot` spec.
