### ISSUE TITLE
Ignoring Custom Tags on TF Resources

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extension-provider-aws#140]
Hi team,

are custom tags currently ignored by the TF reconciliation loop? Specifically: if I add a tag to a `subNet` created by the AWS extension provider.

Regards,
Andreas

/kind question

**Comment by afritzler** [comment]
Ok it seems that Terraform is removing custom tags from my subnets.

Do you guys think it makes sense to allow the user to create a cluster with lets say

```
skipTagSynchronization: true # default: false (DANGERZONE)
```

and exclude the tags from the TF life cycle[0]?

[0] https://www.terraform.io/docs/providers/aws/guides/resource-tagging.html#ignoring-changes-to-specific-tags

**Comment by rfranzke** [comment]
As discussed via Slack, it seems that this might be possible using these constructs:

```hcl
# Terraform 0.12 and later syntax
variable "additional_tags" {
  default     = {}
  description = "Additional resource tags"
  type        = map(string)
}
resource "aws_vpc" "example" {
  # ... other configuration ...
  # This configuration combines some "default" tags with optionally provided additional tags
  tags = merge(
    var.additional_tags,
    {
      Name = "MyVPC"
    },
  )
}
```

If you can confirm that it works as desired I'm open to an adaptation in our infrastructure Terraform script.
/cc @ialidzhikov 
/area usability
/priority normal
/status author-action under-investigation

**Comment by timebertt** [comment]
I just had a quick chat with @afritzler and I propose to leverage the terraform provider AWS functionality to ignore a list of tag keys or tag prefixes for all managed resources, see [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#ignoring-changes-in-all-resources).

The infra config API can be augmented with an optional `ignoreTags` section:
```yaml
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
# ...
ignoreTags:
  keys:
  - SomeCustomKey
  - AnotherCustomKey
  keyPrefixes:
  - user.specific/prefix/
```

Which would result in the following terraform provider config:
```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  // ...
  ignore_tags {
    keys         = ["SomeCustomKey", "AnotherCustomKey"]
    key_prefixes = ["user.specific/prefix/"]
  }
}
```

This way provides more flexibility to users with the prefix approach, while still allowing to add individual ignore keys.
We could think about adding `gardener.cloud/custom/` to the list of ignored prefixes by default.

/touch
/unassign @afritzler 
/assign
