### ISSUE TITLE
Rework the infrastructure integration test with envtest pkg

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#155]
**How to categorize this issue?**

/area testing
/kind enhancement
/priority normal
/platform aws

**Why is this needed**:
Currently the infrastructure integration test directly interacts with the actuator's `Reconcile` and `Delete` funcs which leaves some points uncovered/untested - controller-runtime predicates and controller-runtime inner machinery that afterwards results in `Reconcile` and `Delete` invocations of the actuator. 
Looks like https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest package has a good entry point for integration tests. It allows tests against existing cluster or against partial "ControlPlane" (apiserver and etcd started by the pkg, which might be enough for some cases). We could obtain the environment configuration, create a manager from it, add the controller we want to test to this manager (we already have the `AddToManager` funcs), start the manager and then finally start the test.
I think this will improve the tests as the test will be concentrated more on contract testing (applying and deleting CRs and checking its status) rather than controller/actuator inner working (for example instantiate a chartrenderer and pass it to the `Reconcile` func).

**Comment by timebertt** [comment]
Great idea!
Unfortunately, I haven't taken a deeper look into envtest yet, but I think, it would make sense in general to leverage it for writing integration tests for controllers in g/g :)
