### ISSUE TITLE
least permissions for gardener-extension-provider-aws

### ISSUE THREAD

**Issue by zjj2wry** [gardener/gardener-extension-provider-aws#242]
I want to set the least permissions for gardener-extension-provider-aws in AWS. I want to know where I can find AWS IAM policies. thank you very much

**Comment by ialidzhikov** [comment]
@zjj2wry , I believe this is what you are looking for - ref https://github.com/gardener/gardener-extension-provider-aws/blob/v1.18.0/docs/usage-as-end-user.md#permissions.

**Comment by zjj2wry** [comment]
> @zjj2wry , I believe this is what you are looking for - ref https://github.com/gardener/gardener-extension-provider-aws/blob/v1.18.0/docs/usage-as-end-user.md#permissions.

thank you :))

**Comment by zjj2wry** [comment]
@ialidzhikov S3 permissions are missing from the document
