### ISSUE TITLE
Check if provider-aws can support Shoots with gp3 volumes

### ISSUE THREAD

**Issue by tareqhs** [gardener/gardener-extension-provider-aws#264]
**How to categorize this issue?**

/area storage
/kind enhancement
/priority normal
/platform aws

**What would you like to be added**:

The ability to set volume type in a node worker to gp3. Currently I get this error:
> shoots.core.gardener.cloud "tareqaws6" is forbidden: [spec.provider.workers[2].volume.type: Unsupported value: core.Volume{Name:(*string)(nil), Type:(*string)(0xc0fa264c10), VolumeSize:"100Gi", Encrypted:(*bool)(0xc0772b4ced)}: supported values: "gp2", "io1"]

**Why is this needed**:

I would like to have the benefits of gp3 over gp2.

**Comment by vpnachev** [comment]
This is a configuration change in the CloudProfile. Please, configure properly this volume type similarly how it is done for gp2/io1 in the [example](https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage-as-operator.md#example-cloudprofile-manifest).

/close

**Comment by ialidzhikov** [comment]
@vpnachev did you checked that all involved parties support `gp3`? Does machine-controller-manager can deal with `gp3` volumes?

**Comment by vpnachev** [comment]
I think I have nothing else to check for the reported error:
> shoots.core.gardener.cloud "tareqaws6" is forbidden: [spec.provider.workers[2].volume.type: Unsupported value: core.Volume{Name:(*string)(nil), Type:(*string)(0xc0fa264c10), VolumeSize:"100Gi", Encrypted:(*bool)(0xc0772b4ced)}: supported values: "gp2", "io1"]

If there is really an issue with the gp3 volumes, then it should be properly reported. This one is just missing configuration in the CloudProfile.

**Comment by vpnachev** [comment]
> Hi @vpnachev, is this a landscape-specific issue? where should I proceed from here?

Yes it is. Please, contact your landscape administrators for more details.

**Comment by vlerenc** [comment]
The [validation logic in MCM](https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/validation/awsmachineclass.go#L133) would require a change, right @prashanth26 ?

Most likely, the [dashboard](https://github.com/gardener/dashboard) would be fine, right @grolu ?

Is there another location we would need to touch?

**Comment by prashanth26** [comment]
> The validation logic in MCM would require a change, right @prashanth26 ?

Yes, I suppose this logic would require a change. I have a minor fix to make along the similar lines of code today. I shall enhance this line to check for `gp3` as well for a quick fix.

**Comment by ialidzhikov** [comment]
> > The validation logic in MCM would require a change, right @prashanth26 ?
> 
> Yes, I suppose this logic would require a change. I have a minor fix to make along the similar lines of code today. I shall enhance this line to check for `gp3` as well for a quick fix.

@prashanth26 , isn't the above validation logic applied only for in-tree provider of MCM? With the out-of-tree one I don't see something similar.

**Comment by prashanth26** [comment]
> > > The validation logic in MCM would require a change, right @prashanth26 ?
> > 
> > 
> > Yes, I suppose this logic would require a change. I have a minor fix to make along the similar lines of code today. I shall enhance this line to check for `gp3` as well for a quick fix.
> 
> @prashanth26 , isn't the above validation logic applied only for in-tree provider of MCM? With the out-of-tree one I don't see something similar.

Yes, this is something I just realized after seeing this code. Hence I mentioned the minor fix above. I guess this validation change is something that was missed to migrate with the OOT AWS. I shall fix this right away (and also add this check) and make a hotfix release in the extension as well.

**Comment by ialidzhikov** [comment]
It seems that `gardener-extensionprovider-aws@v1.20.0` already supports gp3 volumes. I was able to successfully validate this locally.

/close
