### ISSUE TITLE
Remove bastion related IAM resources

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#4]
Currently we create the following bastion related IAM resources:

https://github.com/gardener/gardener-extensions/blob/1.0.0/controllers/provider-aws/charts/internal/aws-infra/templates/main.tf#L223-L268

We could remove them and move their creation to g/gardenctl.

**Comment by rfranzke** [comment]
@DockToFuture any update?

**Comment by gardener-botmanager** [comment]
@docktofuture 
<img src="https://source.unsplash.com/collection/981639/640x582">
<details>
<summary>Message</summary>

> /ping @DockToFuture 
> /touch
</details>

**Comment by gardener-botmanager** [comment]
@rfranzke Label "touch" does not exist for this repository.

**Comment by vlerenc** [comment]
@rfranzke Not yet... hold your horses. That was just a dev version. ;-)

**Comment by mvladev** [comment]
I've opened a PR to remove the need for instance profiles when creating AWS bastion nodes in https://github.com/gardener/gardenctl/pull/218

I'll open a PR to remove those IAM resources from the infra
