### ISSUE TITLE
Consider dry run support (if possible) for admission webhook controlplane.aws.extensions.gardener.cloud

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#400]
**How to categorize this issue?**
/area usability
/kind enhancement
/priority 3
/platform aws

**What would you like to be added**:
```
$ k -n shoot--foo--bar get deploy gardener-resource-manager -o yaml > ~/deploy.yaml
$ k -n shoot--foo--bar apply -f ~/deploy.yaml --dry-run=server
for: "deploy.yaml": admission webhook "controlplane.aws.extensions.gardener.cloud" does not support dry run
```

**Comment by dimitar-kostadinov** [comment]
/close

as the issue is fixed with https://github.com/gardener/gardener/pull/4562
and `sideEffects` value is set `None` [here](https://github.com/gardener/gardener/blob/66b1975adf5d6656930d1273c150792028646ad5/extensions/pkg/webhook/registration.go#L55)
