### ISSUE TITLE
Use leases for machine-controller-manager and machine-controller leader election resource lock

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#413]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3
/platform aws

**What would you like to be added**:
Currently machine-controller-manager containers use endpoints as leader election resource lock:

**Why is this needed**:
kubernetes/kubernetes#80289 outlines several good reasons why to choose leases for leader election.

**Comment by rfranzke** [comment]
Part of https://github.com/gardener/gardener/issues/4742

**Comment by acumino** [comment]
gardener/machine-controller-manager#662

**Comment by ialidzhikov** [comment]
We should be good to close this one after https://github.com/gardener/gardener-extension-provider-aws/pull/580 and https://github.com/gardener/gardener-extension-provider-aws/pull/581.

/close
