### ISSUE TITLE
Increase log verbosity of csi-driver-node

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-extension-provider-aws#418]
**How to categorize this issue?**

/area storage logging
/kind enhancement

**What would you like to be added**:

Let's increase the log verbosity of the `csi-driver` container in `csi-driver-node` (at least to 4).

However, on log level 4 and above, csi-driver logs the frequent `NodeGetCapabilities` and `NodeGetVolumeStats` calls (roughly once per 2 minutes for each PV), which are not really that interesting:
```
I0930 13:19:44.947404       1 node.go:498] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:19:44.949556       1 node.go:435] NodeGetVolumeStats: called with args {VolumeId:vol-abcdef VolumePath:/var/lib/kubelet/pods/some-pod-uid/volumes/kubernetes.io~csi/pv-shoot--timebertt--test-some-uid/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:21:09.072947       1 node.go:498] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0930 13:21:09.074569       1 node.go:435] NodeGetVolumeStats: called with args {VolumeId:vol-abcdef VolumePath:/var/lib/kubelet/pods/some-pod-uid/volumes/kubernetes.io~csi/pv-shoot--timebertt--test-some-uid/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

Right now, we don't keep the system-component logs in the logging stack. But once we do, we probably want to filter out these logs.

**Why is this needed**:

We need more logs regarding critical volume operations that operators want to analyze.
Currently `csi-driver-node` is very quiet on log level 3.

**Comment by timebertt** [comment]
cc @dguendisch 

Ah, I see the log level was actually on 5 before it was decreased to 3 with https://github.com/gardener/gardener-extension-provider-aws/pull/347.
@ialidzhikov, do you think it makes sense to increase the verbosity again to have ore information for debugging volume issues?

**Comment by ialidzhikov** [comment]
> @ialidzhikov, do you think it makes sense to increase the verbosity again to have ore information for debugging volume issues?

What is the default log level when you don't specify the flag? And what is the klog recommendation (or aws-ebs-csi-driver recommendation) for log level suitable for production?

The reasons to decrease the log level are more or less described in https://github.com/gardener/gardener-extension-provider-openstack/pull/287. We cannot allow the csi-driver Pod to log millions of log entries for 24h - that's simply a lot for any logging solution.
I can understand that for debugging purposes the current log level can be not enough. But on the other side we have to find the log level that is suitable for production purpose, not for debugging one. So if we want to change the log level, I think we have to do it for all drivers (I assume that they share the same library for grpc from where the logs come from) and we have to make sure that the log entries size is still reasonable and suitable for production.

**Comment by timebertt** [comment]
> What is the default log level when you don't specify the flag?

I assume it is 2. However the help output doesn't specify the default value, so I would have to check it in detail.

> We cannot allow the csi-driver Pod to log millions of log entries for 24h - that's simply a lot for any logging solution.

Yes, that's true. That's why I opened this issue here.
As said, right now there is no logging solution collecting these logs (if I'm not mistaken).
Do you see an issue with increasing the verbosity in this state now?

I assume there are ways to filter out the noisy (and not so interesting logs) as proposed in the original description, once we have such a solution.
Would that be an option?

**Comment by vpnachev** [comment]
>  As said, right now there is no logging solution collecting these logs (if I'm not mistaken).

Not one managed by the Gardener, but shoot owners usually deploy their own application logging stack and it takes care also for the system components and such change can negatively affect them.

**Comment by timebertt** [comment]
That's correct. Valid point

**Comment by dguendisch** [comment]
Maybe we could file a PR upstream to move the boring/periodic stats message from v4 to v5 and would then enable v4 by default? Then the logs would only include volume mount + unmount, which should be pretty limited in their amount.

**Comment by istvanballok** [comment]
The logging library `klog` supports a file name based verbosity setting - it could help to focus on the relevant logs.
See https://github.com/kubernetes/klog/blob/9ad246211af1ed84621ee94a26fcce0038b69cd1/klog.go#L442
