### ISSUE TITLE
`srcAndDstChecksEnabled` MachineClass field is not set for K8s >= 1.22 clusters

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#444]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3
/platform aws

**What happened**:
@himanshu-kun found that https://github.com/gardener/gardener-extension-provider-aws/pull/386 is actually incomplete. It sets only a value in the machineclass values but this value itself is not used in the machineclass template.

**What you expected to happen**:
The `srcAndDstChecksEnabled` field to be set to the appropriate value for K8s >= 1.22 clusters.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a K8s 1.22 cluster

2. Make sure that the corresponding MachineClass does not have the `srcAndDstChecksEnabled` field set.

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.30.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by AxiomSamarth** [comment]
Thanks, @ialidzhikov. I will raise a PR with the correction.
