### ISSUE TITLE
`/test` command wrongly adds the test label

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#483]
**How to categorize this issue?**

/area dev-productivity
/kind bug
/platform aws

**What happened**:
Currently we use `/test` command to trigger integration test on PRs. gardener-robot also interprets this command as user wants to  add the test label -> it adds the `kind/test` label to the PR.

**What you expected to happen**:
To do not have this collision. When I want to trigger the integration tests, I don't want to add the `kind/test` label to the PR.

**How to reproduce it (as minimally and precisely as possible)**:
Sea above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by neo-liang-sap** [comment]
Hi @vlerenc ,
Regarding this issue, the ultimate aim is when `/test` entered as comment in an issue, `kind/test` label will not be added.
I investigated this issue, `/test` is determined to associate with `kind/test` in https://github.tools.sap/kubernetes/gardener-robot/blob/master/robot/bots/commands.py#L44
I propose following solution:

1) add extra logic in https://github.tools.sap/kubernetes/gardener-robot/blob/master/robot/bots/commands.py#L44 like 
```
if label.endswith("/" + arg) and arg != "test":
  return EntityLabeler.IDENTIFIER_LABEL_SEGMENT, label
```
this doesn't look beautiful as `commands.py` is kind of base command class for all commands

2) remove `kind/test` from config.yaml -> this seems unacceptable as `kind/test` is still needed in some scenario when issue is truly test case

3) add a `test.py` in https://github.tools.sap/kubernetes/gardener-robot/tree/master/robot/commands which actually add a command named `test` but in `exec` function defines nothing e.g. only a `pass` statement there

What do you think? or maybe other better solution here?

thanks!
-Neo

**Comment by neo-liang-sap** [comment]
sent email to @vlerenc for discussion regarding how to implement this

**Comment by neo-liang-sap** [comment]
issue is fixed and merged in https://github.tools.sap/kubernetes/gardener-robot/pull/245
/close
