### ISSUE TITLE
Impossible to configure iops for gp3 disk type on AWS

### ISSUE THREAD

**Issue by i033653** [gardener/gardener-extension-provider-aws#488]
**How to categorize this issue?**
  /area storage

/kind bug
/platform aws

**What happened**:
By configuring the disk type of gp3 in AWS, I want to increase the number of iops from default 3,000 to a higher number.
This is possible in AWS as described on the attached screenshot.
However, it is not possible to configure it in shoot yaml. See the error below.
Could not save worker configuration
admission webhook "validation.aws.provider.extensions.gardener.cloud" denied the request: spec.provider.workers[3].providerConfig.volume.iops: Forbidden: setting iops is only allowed if volume type is "**gp2**" or "io1"
BTW, for gp2 volume type it is not possible to configure iops. So it seems there is confusion between gp2 and gp3 in the validation.
In addition, I want to configure the Throughput (MiB/s) as it is exposed by AWS for gp3. Is this option exposed by Gardener?
![image](https://user-images.githubusercontent.com/34998331/151982030-2b3471b2-2efa-43bf-81d5-75c839d04fd9.png)
![image](https://user-images.githubusercontent.com/34998331/151982078-b7b775ab-4ac1-476a-b4c8-941855097ff4.png)

- Kubernetes version (use `kubectl version`): 1.21.7

**Comment by dkistner** [comment]
Indeed the iops should be configurable for `gp3`.
Actually I don't like at all that this configuration is hard coded [ref](https://github.com/gardener/gardener-extension-provider-aws/blob/master/pkg/apis/aws/validation/worker.go#L117-L128)

For now we can simply extend the validation by adding a case for `gp3` in the switch, but afaik `gp3` has variable iops depending on the disk size.

**Comment by i033653** [comment]
raising the priority to "2" since it blocks us from using a much more cost-effective disk.
/priority 2

**Comment by nachshv** [comment]
Hi guys
Any progress with this issue? without a way to configure the iops and throughput we cannot make use of gp3 which is much cheaper than gp2 in our use case (BAS).

**Comment by himanshu-kun** [comment]
We have noticed that we currently put a hard-coded limit on the iops range for different types of volumes [refer [this](https://github.com/gardener/gardener-extension-provider-aws/blob/ba74de65939d0df41a8ae205ff6cee0509fd7408/pkg/apis/aws/validation/worker.go#L117-L128)]
The problem with this is that this range could keep on changing with time , like for gp2 now the max is 16000 (refer https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#:~:text=KiB%20I/O)-,16%2C000,-256%2C000
So could we not leave this kind of validation for the provider itself once it gets the creation request for the volume and here we just do the basic validation like non-positive not allowed ?

cc @rfranzke @dkistner @unmarshall

**Comment by unmarshall** [comment]
> So could we not leave this kind of validation for the provider itself once it gets the creation request for the volume and here we just do the basic validation like non-positive not allowed ?

If at all range needs to he checked against [min, max] then it should be done in MCM provider extension where provider APIs can be used to get the range for a given volume type. However, as @himanshu-kun  has already mentioned we can completely remove this check and let an error be returned by the provider if the requested IOPS is not within an allowed range for a volume type. We do this also for GPU configuration.

**Comment by dkistner** [comment]
Yes I agree. We can delegate iops validation to the aws. The downside is of course that feedback will arrive once the volume is created.

**Comment by himanshu-kun** [comment]
we will be proceeding with the following plan then:

in extension-aws:
- do minimal validation (eg. values are positive) for iops
- `disallow iops for gp2 volumes`, as its not configurable as per AWS and gets assigned value based on volume size (3*volumeSize)
-  keep the io1 volume iops logic same where user must provide iops
- gp3 volume has option to be provided or not, incase its not provided, or provided a value <= 3000 , AWS would set default value of 3000 iops(as confirmed by experiments) and other cases the provided values are respected.

in provider-aws:
- do minimal validation for iops
- allow iops to be configurable for gp3 volumes


cc @rishabh-11 @kon-angelo
