### ISSUE TITLE
Enable aws LB controller

### ISSUE THREAD

**Issue by yang-wang11** [gardener/gardener-extension-provider-aws#545]
**How to categorize this issue?**

/area Enable aws LB controller([aws-load-balancer-controller ](https://github.com/kubernetes-sigs/aws-load-balancer-controller/)) instead of  [serviceController](https://github.com/kubernetes/kubernetes/tree/release-1.9/pkg/controller/service)  of CCM
/kind enhancement
/platform aws

**What would you like to be added**:
deploy new service `aws-load-balancer-controller`

**Why is this needed**:
Fast support new feature of AWS LB service, link https://github.com/kubernetes/cloud-provider-aws/issues/343

**Comment by dkistner** [comment]
Hi @yang-wang11,

thanks for opening this request. I'm not familiar with the `aws-load-balancer-controller`, but before we can do something in this direction we first need answers to your enhancement request here: https://github.com/kubernetes/enhancements/issues/3296

Only if there are means to disable ccm `service` controller we can safely run another controller that take care about services of type `LoadBalancer`. I'm also wondering if we in this case then not simply want to provide cluster owners the ability to disable the `service` controller of the respective ccm and then deploy the custom lb controller own their own.

**Comment by MartinWeindel** [comment]
> Only if there are means to disable ccm `service` controller we can safely run another controller that take care about services of type `LoadBalancer`. I'm also wondering if we in this case then not simply want to provide cluster owners the ability to disable the `service` controller of the respective ccm and then deploy the custom lb controller own their own.

There is already a mechanism for that: by setting the annotation `service.beta.kubernetes.io/aws-load-balancer-type=external`, the `service` of type `LoadBalancer` is not handled by the CCM. See [isLBExternal](https://github.com/kubernetes/cloud-provider-aws/blob/ef421577ebb65a995c5cc044a266eb590cfcd59f/pkg/providers/v1/aws_loadbalancer.go#L83) and [EnsureLoadBalancer](https://github.com/kubernetes/cloud-provider-aws/blob/1afaa94c9d7ef33ff9076df34266c1fb2d2f66b8/pkg/providers/v1/aws.go#L4047)

**Comment by yang-wang11** [comment]
After using the spec below in Shoot 
```yaml
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      loadBalancerController:
        enabled: true    
```
I hit the below issue in https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-hc-dev/, is we need to enable some toggle before enabling this feature?
```yaml
Error from server: error when creating "shoot-aws.yaml": admission webhook "mutation.aws.provider.extensions.gardener.cloud" denied the request: strict decoding error: unknown field "loadBalancerController"
```
@kon-angelo  @MartinWeindel  Do you mind sharing your insight about it?
