### ISSUE TITLE
Impossible to configure "Throughput (MiB/s)" for gp3 disk type on AWS

### ISSUE THREAD

**Issue by i033653** [gardener/gardener-extension-provider-aws#584]
/area storage
/platform aws

By configuring the disk type of gp3 in AWS,  to configure the **Throughput (MiB/s)** as it is exposed by AWS for gp3.
This is possible in AWS as described on the attached screenshot.
However, it is not possible to configure it in shoot yaml. 

This feature will help us (BAS) to achieve better performance by using gp3 disks.

![image](https://user-images.githubusercontent.com/34998331/182153751-a8dea908-df24-4701-b14c-d60022e5b175.png)

**Comment by rishabh-11** [comment]
We have picked up this topic and wanted to know if there are any other fields as well that you would like to be configurable.

**Comment by i033653** [comment]
> We have picked up this topic and wanted to know if there are any other fields as well that you would like to be configurable. @i033653

hi @rishabh-11 . Currently, this is only the field we would like to be customized.

**Comment by nachshv** [comment]
hi @rishabh-11 

Any ETA for this change?

**Comment by rishabh-11** [comment]
> hi @rishabh-11
> 
> Any ETA for this change?

hi @nachshv 
I will raise the PRs by tomorrow end of day.
