### ISSUE TITLE
SSH to machines of type amd64 does not work

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardener-extension-provider-aws#694]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/platform aws

**What happened**:
I wanted to ssh to a machine of architecture type `amd64` (c3.2xlarge) with gardenctl and currently it's not possible.
The CR shows the following error:

```
status:
  lastError:
    description: "Error reconciling Bastion: failed to ensure bastion instance: failed
      to run instance: InvalidParameterValue: The architecture 'x86_64,i386' of the
      specified instance type does not match the architecture 'arm64' of the specified
      AMI. Specify an instance type and an AMI that have matching architectures, and
      try again. You can use 'describe-instance-types' or 'describe-images' to discover
      the architecture of the instance type or AMI.\n\tstatus code: 400, request id:
      c1b2abb2-cf06-4024-8ac6-9cc980537b13"
    lastUpdateTime: "2023-02-03T10:21:30Z"
  lastOperation:
    description: "Error reconciling Bastion: failed to ensure bastion instance: failed
      to run instance: InvalidParameterValue: The architecture 'x86_64,i386' of the
      specified instance type does not match the architecture 'arm64' of the specified
      AMI. Specify an instance type and an AMI that have matching architectures, and
      try again. You can use 'describe-instance-types' or 'describe-images' to discover
      the architecture of the instance type or AMI.\n\tstatus code: 400, request id:
      c1b2abb2-cf06-4024-8ac6-9cc980537b13"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by tedteng** [comment]
I like to take a look 
/assign

**Comment by tedteng** [comment]
identify the issue due to the latest AMI Image `gardenlinux-aws-gardener_prod-arm64` base on Architecture "arm64" not matching with the instance type t2.nano. will look for a suitable instance type to match the Architecture "arm64"
