### ISSUE TITLE
*-packr.go files are ignored by git

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#81]
**What happened**:
Currently changes in `charts/images.yaml` are not applied in the docker image if `make generate` is not run.
Also `check-generate` won't detect any outdated generated file.

**What you expected to happen**:
After updating an entry in `charts/images.yaml` and building a docker image after that, I would expect my change to be respected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Update an image tag in `charts/images.yaml`

For example update the `csi-snapshotter` image tag from `v2.1.0` to `v2.1.1`

```diff
 - name: csi-snapshotter
   sourceRepository: github.com/kubernetes-csi/external-snapshotter
   repository: quay.io/k8scsi/csi-snapshotter
-  tag: "v2.1.0"
+  tag: "v2.1.1"
```

2. Build and push an image

```
$ docker build -t foo/gardener-extension-provider-aws:bar -f Dockerfile --target gardener-extension-provider-aws .
$ docker push foo/gardener-extension-provider-aws:bar
```

3. Update the ControllerRegistration with the newly built image and ensure that the `charts/images.yaml` file in the new container is updated with the change from step 1.

4. Ensure that the update step from step 1 has no effect and the extension controller is using the old tag (`v2.1.0`).

To fix this issue, the developer needs to first run `make generate` and then to build and push his docker image.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Either we clean the packr files when building the image (that should work, or?), or we add the `generate` rule to https://github.com/gardener/gardener-extension-provider-aws/blob/master/Dockerfile#L6. WDYT?

**Comment by johananl** [comment]
Just got bitten by this. One thing which makes this even trickier is the fact that the generated file is gitignored, which made me *think* `make generate` didn't do anything where in fact it did. I'll open a PR for this.

**Comment by johananl** [comment]
Personally I think it's better to commit generated files because I like the idea of being able to simply run `make` and have things working. We could achieve the same "UX" also without committing generated files but then we have to ensure the `generate` target is always run before building.

**Comment by ialidzhikov** [comment]
Fixed with https://github.com/gardener/gardener-extension-provider-aws/pull/316.
