### ISSUE TITLE
Infrastructure reconciliation should validate user-configured DHCP options

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-aws#85]
**What would you like to be added**:
If the user provides a VPC ID then the `Infrastructure` controller already performs certain checks. For example, it validates that the VPC has an attached internet gateway.
Let's extend these checks by a new one that validates the associated DHCP options. Particularly, we should enforce that the configured `domain-name` property is `ec2.internal` for `us-east-1` region while it is `<region-name>.compute.internal` for all other regions.

Ref: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html

/cc @MartinWeindel 

**Why is this needed**:
Prevent the user from misconfiguring the shoot clusters and provide helpful/meaningful error messages instead.

**Comment by MartinWeindel** [comment]
fixed with #644
