### ISSUE TITLE
Validate cloudprovider credentials 

### ISSUE THREAD

**Issue by dansible** [gardener/gardener-extension-provider-aws#90]
(recreating issue from the g/g repo: https://github.com/gardener/gardener/issues/2293)

**What would you like to be added**:
Add validation for `cloudprovider` secret

**Why is this needed**:
Currently, when uploading secrets via the UI, all secret fields are required and validated. However, when creating those credentials via the `cloudprovider` secret, there is no validation. This results in errors such as this error: (specific to Azure but a similar error would be generated for AWS):

```
Flow "Shoot cluster reconciliation" encountered task errors: [task "Waiting until shoot infrastructure has been reconciled" failed: failed to create infrastructure: retry failed with context deadline exceeded, last error: extension encountered error during reconciliation: Error reconciling infrastructure: secret shoot--xxxx--xxxx/cloudprovider doesn't have a subscription ID] Operation will be retried.
```

<img width="682" alt="Screen Shot 2020-05-07 at 1 09 03 PM" src="https://user-images.githubusercontent.com/25449094/81323880-1b74f300-9064-11ea-87c9-d3fc165fa6a1.png">

**Comment by ialidzhikov** [comment]
My current approach/idea:

1. The cloud provider credentials are `v1/Secret` - there isn't something (except the `.data` keys) to distinguish it from the other Secrets in the project namespace. Currently we have a `ValidatingWebhookConfiguration` that handles `CREATE` and `UPDATE` for `Shoot`s so we could have the credentials validation (ensure that the required keys are present, non-empty and match given pattern) on Shoot creation. Shoot `.spec.secretBindingName` is immutable, SecretBinding `.spec.secretRef` is also immutable which kind of ensures that once the Shoot created the referred Secret won't be changed - so we can skip the credentials validation on UPDATE.

2. The data of Secret holding the credentials can be updated -> existing required `.data` keys can be removed. We can have additional webhook that handles `UPDATE` for `Secret`s and checks whether the Secret is used by a Shoot from the given provider type and if yes, preforms the credentials validation. If would be very nice if in this case we can handle cloud provider account update which happens with the secrets update and forbid it - ref #40.

**Comment by rfranzke** [comment]
+1

**Comment by vpnachev** [comment]
Excuse me for the delay - the plan sounds very good to me.
